/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/x3SZplIlIXe
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { CarouselItem, CarouselContent, CarouselPrevious, CarouselNext, Carousel } from "@/components/ui/carousel"
import { Button } from "@/components/ui/button"

export function VenueDetails() {
  return (
    <div className="flex flex-col gap-12 max-w-6xl mx-auto px-4 md:px-6 py-12 md:py-20">
      <div className="grid md:grid-cols-2 gap-8">
        <div className="grid gap-4">
          <h1 className="text-3xl font-bold">The Grand Ballroom</h1>
          <div className="grid md:grid-cols-2 gap-4">
            <div>
              <h3 className="text-lg font-semibold">Location</h3>
              <p className="text-gray-500 dark:text-gray-400">123 Main St, Anytown USA 12345</p>
              <Link className="text-gray-900 hover:underline dark:text-gray-50" href="#">
                View on Map
              </Link>
            </div>
            <div>
              <h3 className="text-lg font-semibold">Capacity</h3>
              <p className="text-gray-500 dark:text-gray-400">500 guests</p>
            </div>
            <div>
              <h3 className="text-lg font-semibold">Contact</h3>
              <p className="text-gray-500 dark:text-gray-400">
                <a className="hover:underline" href="#">
                  (123) 456-7890
                </a>
              </p>
              <p className="text-gray-500 dark:text-gray-400">
                <a className="hover:underline" href="#">
                  info@theballroom.com
                </a>
              </p>
              <Link className="text-gray-900 hover:underline dark:text-gray-50" href="#">
                Visit Website
              </Link>
            </div>
          </div>
        </div>
        <Carousel className="rounded-lg overflow-hidden">
          <CarouselContent>
            <CarouselItem>
              <img
                alt="Venue Exterior"
                className="aspect-video object-cover"
                height={600}
                src="/placeholder.svg"
                width={800}
              />
            </CarouselItem>
            <CarouselItem>
              <img
                alt="Venue Interior"
                className="aspect-video object-cover"
                height={600}
                src="/placeholder.svg"
                width={800}
              />
            </CarouselItem>
            <CarouselItem>
              <img
                alt="Event Setup"
                className="aspect-video object-cover"
                height={600}
                src="/placeholder.svg"
                width={800}
              />
            </CarouselItem>
          </CarouselContent>
          <CarouselPrevious />
          <CarouselNext />
        </Carousel>
      </div>
      <div className="grid gap-8">
        <div>
          <h2 className="text-2xl font-bold">About The Grand Ballroom</h2>
          <p className="text-gray-500 dark:text-gray-400 mt-4">
            The Grand Ballroom is a stunning event venue located in the heart of the city. With its elegant, historic
            architecture and spacious layout, the ballroom is the perfect setting for a variety of events, from lavish
            weddings to corporate galas. The venue boasts high ceilings, ornate chandeliers, and a grand staircase that
            creates a truly impressive atmosphere.
          </p>
          <p className="text-gray-500 dark:text-gray-400 mt-4">
            In addition to the main ballroom, the venue offers a range of flexible event spaces, including a cozy
            lounge, a private dining room, and a beautifully landscaped outdoor terrace. The in-house catering team is
            renowned for their exceptional cuisine and personalized service, ensuring that every event is a memorable
            experience.
          </p>
        </div>
        <div>
          <h2 className="text-2xl font-bold">Key Features</h2>
          <ul className="grid gap-4 mt-4">
            <li className="flex items-start gap-4">
              <CheckIcon className="text-gray-900 w-6 h-6 shrink-0 dark:text-gray-50" />
              <div>
                <h3 className="text-lg font-semibold">Elegant Architecture</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  The Grand Ballroom's historic architecture, with its high ceilings, ornate chandeliers, and grand
                  staircase, creates a truly impressive and memorable atmosphere.
                </p>
              </div>
            </li>
            <li className="flex items-start gap-4">
              <CheckIcon className="text-gray-900 w-6 h-6 shrink-0 dark:text-gray-50" />
              <div>
                <h3 className="text-lg font-semibold">Outdoor Terrace</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  The venue's beautifully landscaped outdoor terrace provides a serene and picturesque setting for
                  cocktail receptions, small gatherings, or simply enjoying the fresh air.
                </p>
              </div>
            </li>
            <li className="flex items-start gap-4">
              <CheckIcon className="text-gray-900 w-6 h-6 shrink-0 dark:text-gray-50" />
              <div>
                <h3 className="text-lg font-semibold">Exceptional Catering</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  The in-house catering team is renowned for their exceptional cuisine and personalized service,
                  ensuring that every event is a culinary delight.
                </p>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <div className="grid md:grid-cols-2 gap-8">
        <div>
          <h2 className="text-2xl font-bold">Pricing</h2>
          <p className="text-gray-500 dark:text-gray-400 mt-4">
            The Grand Ballroom offers a range of pricing options to suit your event needs. Rates are based on the event
            date, guest count, and selected services. Please contact us for a personalized quote.
          </p>
          <Button className="mt-4">Request a Quote</Button>
        </div>
        <div>
          <h2 className="text-2xl font-bold">Upcoming Events</h2>
          <div className="grid gap-4 mt-4">
            <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4">
              <h3 className="text-lg font-semibold">Corporate Gala</h3>
              <p className="text-gray-500 dark:text-gray-400">June 15, 2023 | 6:00 PM - 11:00 PM</p>
              <Button size="sm" variant="link">
                Learn More
              </Button>
            </div>
            <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4">
              <h3 className="text-lg font-semibold">Wedding Reception</h3>
              <p className="text-gray-500 dark:text-gray-400">July 1, 2023 | 4:00 PM - 10:00 PM</p>
              <Button size="sm" variant="link">
                Learn More
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  )
}
